# Generated by Django 3.1.3 on 2020-12-07 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default=None, max_length=50, null=True)),
                ('address', models.CharField(default=None, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_score', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number_group', models.CharField(max_length=4)),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_hobby', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.PositiveSmallIntegerField()),
                ('contact_info', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='cw_22.contactinfo')),
                ('diary', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='cw_22.diary')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='cw_22.group')),
                ('hobbies', models.ManyToManyField(related_name='students', to='cw_22.Hobby')),
            ],
        ),
        migrations.CreateModel(
            name='StudentHobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cw_22.hobby')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cw_22.student')),
            ],
            options={
                'db_table': 'student_hobby',
                'unique_together': {('student', 'hobby')},
            },
        ),
    ]
