# Generated by Django 3.1.3 on 2020-12-07 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cw_22', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('number_of_pages', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cw_22.book')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cw_22.student')),
            ],
            options={
                'db_table': 'cw_22_student_book',
                'unique_together': {('student', 'book')},
            },
        ),
        migrations.DeleteModel(
            name='StudentHobby',
        ),
    ]
