# Generated by Django 3.1.3 on 2020-12-07 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cw_22', '0002_auto_20201207_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='cw_22.book'),
        ),
    ]
