# Generated by Django 3.1.3 on 2020-12-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw_21', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.SmallIntegerField()),
                ('profession', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
