# Generated by Django 3.1.3 on 2020-12-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw_21', '0002_auto_20201206_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
